name: Build docs

on:
  repository_dispatch:
  workflow_dispatch:

jobs:
  build-kelp:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare dirs
        run: |
          mkdir kelp
          mkdir agar
          mkdir build
          cd build
          
      - name: Get the docs repo
        uses: actions/checkout@v2
        with: 
          repository: kelp-lang/docs
          path: build
        
      - name: Move to kelp mdbook
        run: |
          ls -lAh
          cd kelp/

      - name: Build kelp mdBook
        uses: peaceiris/actions-mdbook@v1.1.13
        
      - name: Copy book to root
        run: |
          cp -r book/* $GITHUB_WORKSPACE/kelp/*
      
      - name: Move to agar mdbook
        run: |
          cd ..
          ls -lAh
          cd agar/
      
      - name: Build kelp mdBook
        uses: peaceiris/actions-mdbook@v1.1.13

      - name: Copy book to root
        run: |
          cp -r book/* $GIHUB_WORKSPACE/agar/*
      
      - name: Clean up and move to root again
        run: |
          cd $GITHUB_WORKSPACE
          rm -rf build
      
      - name: Build github pages
        uses: crazy-max/ghaction-github-pages@v2.2.0
        with:
          build-dir: docs
