name: Build docs

on:
  repository_dispatch:
  workflow_dispatch:

jobs:
  build-kelp:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare dirs
        run: |
          mkdir kelp
          mkdir agar
          mkdir build
          
      - name: Get the docs repo
        uses: actions/checkout@v2
        with: 
          repository: kelp-lang/docs
          path: build

      - name: Build kelp mdBook
        uses: XAMPPRocky/deploy-mdbook@v1.1.0
        with:
          workspace: build/kelp/
          build_only: true
        
      - name: Copy book to root
        run: cp -r build/kelp/book/* $GITHUB_WORKSPACE/kelp/*
      
      
      - name: Build kelp mdBook
        uses: XAMPPRocky/deploy-mdbook@v1.1.0
        with:
          workspace: build/agar/
          build_only: true

      - name: Copy book to root
        run: |
          cp -r build/agar/book/* $GIHUB_WORKSPACE/agar/*
      
      - name: Clean up and move to root again
        run: rm -rf build
      
      - name: Build github pages
        uses: crazy-max/ghaction-github-pages@v2.2.0
        with:
          build-dir: docs
